export default {
    GROUPS_RECEIVED : 'GROUPS_RECEIVED',
    TEAM_RECEIVED : 'TEAM_RECEIVED',
    MATCH_TODAY_RECEIVED: 'MATCH_TODAY_RECEIVED',
    MATCH_TOMORROW_RECEIVED: 'MATCH_TOMORROW_RECEIVED'
}